language: node_js
node_js:
  - "8.11.3"
  env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/tabes
  before_script:
  - psql -c 'create database  tabes;' -U postgres
  - psql -U postgres -d tabes -a -f tabes.sql
  addons:
    apt:
    packages:
    - postgresql-server-dev-9.2